version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/geosearch-bundle"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/geosearch-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/leaflet-opencage-geosearch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/ol-opencage-geosearch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples/react-example"
    schedule:
      interval: "weekly"
